" Vim plug stuff: pluginns will be downloaded under the directory
call plug#begin('~/.vim/plugged')

" Declare the list of plugins
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'

call plug#end()

" show existing tab with 4 spaces width
set tabstop=4

" when indenting with '>', use 4 spaces width
set shiftwidth=4

" On pressing tab, insert 4 spaces
set expandtab

syntax on
filetype plugin indent on

" Short esc key timeout
set timeoutlen=1000 ttimeoutlen=0

" More natural split opening
set splitbelow
set splitright

set nu
set cursorline
set ruler
set ignorecase
set smartcase
set hlsearch
set wildmenu

" Set syntax highlighting for markdown
let g:markdown_fenced_languages = ['html', 'py=python', 'sh=bash', 'julia', 'c', 'cpp', 'rust']

" change semi colon to colon in normal mode
nnoremap ; :

" Posssibly faster scrolling
set ttyfast

" Faster navigation between splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" =======vim-airline=====
let g:airline_section_b = '%{strftime("%c")}'
let g:airline_section_y = 'BN: %{bufnr("%")}'

" Set leader as ,
let mapleader=","

let g:NERDTrimTrailingWhitespace = 1

